// <auto-generated />
using System;
using CryptoCurrency.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptoCurrency.Migrations
{
    [DbContext(typeof(DbContextApplication))]
    [Migration("20240312235909_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CryptoCurrency.Models.CryptocurrencyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("ChangePercent24Hr")
                        .HasColumnType("float");

                    b.Property<double?>("MarketCapUsd")
                        .HasColumnType("float");

                    b.Property<double?>("MaxSupply")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PriceUsd")
                        .HasColumnType("float");

                    b.Property<string>("Rank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Supply")
                        .HasColumnType("float");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("VolumeUsd24Hr")
                        .HasColumnType("float");

                    b.Property<double?>("Vwap24Hr")
                        .HasColumnType("float");

                    b.Property<int?>("action")
                        .HasColumnType("int");

                    b.Property<string>("id_text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrencies");
                });

            modelBuilder.Entity("CryptoCurrency.Models.DeletedCryptocurrency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCrypto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCrypto")
                        .IsUnique();

                    b.ToTable("DeletedCryptocurrencies");
                });

            modelBuilder.Entity("CryptoCurrency.Models.DeletedCryptocurrency", b =>
                {
                    b.HasOne("CryptoCurrency.Models.CryptocurrencyModel", "Crypto")
                        .WithOne()
                        .HasForeignKey("CryptoCurrency.Models.DeletedCryptocurrency", "IdCrypto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crypto");
                });
#pragma warning restore 612, 618
        }
    }
}
